version: '3.8'

services:
  backend:
    image: python:3.10-slim
    working_dir: /app
    volumes:
      - ./backend:/app
    command: sh -c "pip install flask && python app.py"
    ports:
      - "5000:5000"

  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "8090:80"