pipeline {
  agent {
    docker {
      image 'docker/compose:1.29.2'
      args '-v /var/run/docker.sock:/var/run/docker.sock -v $PWD:/app -w /app'
    }
  }

  stages {
    stage('Start Services') {
      steps {
        sh 'docker-compose up -d'
      }
    }
  }
}
