pipeline {
  agent any

  stages {
    stage('Start Services') {
      steps {
        dir('multi-stage-multi-agent') { // adjust if needed
          sh 'docker compose up -d'
        }
      }
    }
  }
}
